<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.9" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AreWeDoomd.Application\AreWeDoomd.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Common\Email\**\*.cs" />
    <Compile Update="Common\Options\**\*.cs" />
    <Compile Update="Common\Repositories\**\*.cs" />
    <Compile Update="Common\Services\**\*.cs" />
    <Compile Update="Common\Persistence\Configurations\PasswordResetRequestConfiguration.cs" />
  </ItemGroup>

</Project>

